operators:
  rhods-operator:
    channel: stable-3.x
    namespace: redhat-ods-operator
    installPlanApproval: Automatic
    startingCSV: rhods-operator.3.4.0
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      enabled: true
